import type { Metadata } from "next";
import { Inter, Barlow, Barlow_Condensed, Bellefair } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const bellefair = Bellefair({
  subsets: ["latin"],
  weight: "400"
});

const barlow = Barlow({
  subsets: ["latin"],
  weight: "400"
});

const barlow_condensed = Barlow_Condensed({
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Space tourism website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
